# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ian Hu
email: ianhu@ianhu.me
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Ian Hu | Software engineering student from the University of Waterloo.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ianhu.ca" # the base hostname & protocol for your site
twitter_username: NoTwitter
github_username:  ian952

# Build settings
markdown: kramdown
